//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canvas.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Canvas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Windows.Forms;
        ///
        ///namespace Canvas
        ///{
        ///	class CursorCollection
        ///	{
        ///		Dictionary&lt;object, Cursor&gt; m_map = new Dictionary&lt;object, Cursor&gt;();
        ///		public void AddCursor(object key, Cursor cursor)
        ///		{
        ///			m_map[key] = cursor;
        ///		}
        ///		public void AddCursor(object key, string resourcename)
        ///		{
        ///			string name = &quot;Resources.&quot; + resourcename;
        ///			Type type = GetType();
        ///			Cursor cursor = new Cursor(GetType(), name);
        ///			m_map[key] =  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CursorCollection {
            get {
                return ResourceManager.GetString("CursorCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap drawtoolimages {
            get {
                object obj = ResourceManager.GetObject("drawtoolimages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edittoolimages {
            get {
                object obj = ResourceManager.GetObject("edittoolimages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] hmove {
            get {
                object obj = ResourceManager.GetObject("hmove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Drawing;
        ///using System.Windows.Forms;
        ///
        ///namespace Canvas
        ///{
        ///	class ImagesUtil
        ///	{
        ///		static public ImageList GetToolbarImageList(Type type, string resourceName, Size imageSize, Color transparentColor)
        ///		{
        ///			System.Drawing.Bitmap bitmap = new System.Drawing.Bitmap(type, resourceName);
        ///			ImageList imageList = new ImageList();
        ///			imageList.ImageSize = imageSize;
        ///			imageList.TransparentColor = transparentColor;
        ///			imag [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap menuimages {
            get {
                object obj = ResourceManager.GetObject("menuimages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
